default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: myapp_development

development_queue:
  <<: *default
  database: myapp_development_queue

test:
  <<: *default
  database: myapp_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] || "postgresql://postgres:password@db:5432/myapp_production" %>
  
  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] || "postgresql://postgres:password@db:5432/myapp_production_cache" %>
  
  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] || "postgresql://postgres:password@db:5432/myapp_production_queue" %>
  
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] || "postgresql://postgres:password@db:5432/myapp_production_cable" %>
